---
title: "Resume"
---

**Gwynyn Hayes** \|Eatonville, WA \| (219) 921-9970 \| hayes5[\@stolaf.edu](mailto:Math1@stolaf.edu) \|

**EDUCATION**

St. Olaf College, Northfield, MN				             Expected Graduation: May 2026

Bachelor of Arts: Computer Science; Concentrations: Statistics & Data Science; GPA: X.XX

Relevant Coursework: Linear Algebra, Calculus 1 and 2,  Data Science 1 and 2, Statistics 1 and 2, Algorithms for Decesion Making, Discrete Mathematical Reasoning, Advanced Statistical Modeling\

**SKILLS** 

Technical: Intermediate proficiency in R and Python; basic proficiency in Go, Rust, C++, C, Prolog and SQL  

Languages: English (native fluency written/spoken); French (basic written, conversational spoken) 

**JOB EXPERIENCE**

Statistics 1 Grader, Statistics 1(SDS 172), St. Olaf College, Northfield, MN                           January 2024 

-   Graded and provided feedback on homework assignments to further improve future studies 

-   Worked with a quick turn around time as this was a month long course covering an entire semesters worth of material

Costume Shop Worker, St. Olaf College, Northfield, MN                              September 2024 - May 2026 

-   Designed and constructed costumes for theater department shows

-   Worked closely with a team to meet tight deadlines and quickly solve complex problems

-   Gained creative design skill to think in both 2-dimensions and 3-dimensions and the transfer between the two. 

Nature Camp Instructor, Tacoma Nature Center, Tacoma, WA         June-August 2024 / June-August 2025

-   Worked with a small team to plan and teach an environmental education program to children ages 6-12  

-   Gained knowledge of the natural history and science of the local area.  I developed curriculum to accommodate a wide variety of knowledge and interest levels, in environmental science, adapting quickly to the needs of the group.

-   Developed quick problem solving and time management skills to keep everything on schedule due to having to adapt in a very fast paced environment.

Camp Counsleor, YMCA Camp Orkila,  Eastsound, WA                                           June - August 2023  

-   Worked with campers, ages 8-10, managing their emotional, physical, and social well-being.

-   Organized and led different activities in all program areas. I developed and implemented strategies to foster a sense of community and teamwork among campers, encouraging inclusivity and collaboration during all camp activities. 

-   Adapted to new work partners regularly in a fast-paced environment.