<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Women’s Participation in Global Climate Conferences – Gwynnie’s Epic Website!</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-510461f684b7e25beac7317ea143e9da.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Gwynnie’s Epic Website!</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-computer-science" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Computer Science</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-computer-science">    
        <li>
    <a class="dropdown-item" href="../csproject.html">
 <span class="dropdown-text">Ethics of Remote Sensing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tabs/Yarn!.html">
 <span class="dropdown-text">Yarn!</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-science" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data Science</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-data-science">    
        <li>
    <a class="dropdown-item" href="../tabs/miniproj1.html">
 <span class="dropdown-text">Frogs and Forest Mapping</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tabs/miniproj2.html">
 <span class="dropdown-text">Wildfire Web Scraping</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tabs/salmon_tummys.html">
 <span class="dropdown-text">Diets of Juvenile Chinhook Salmon in PNW</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tabs/mp4.html">
 <span class="dropdown-text">Illuminati Hotties Text Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tabs/Wildfires.html">
 <span class="dropdown-text">Wildfires</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-statistics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Statistics</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-statistics">    
        <li>
    <a class="dropdown-item" href="../tabs/Stats2Project/finalProject.html">
 <span class="dropdown-text">Frog vs Toad Identification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tabs/stats3project.html">
 <span class="dropdown-text">Women’s Participation in Global Climate Conferences</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#materials-methods" id="toc-materials-methods" class="nav-link" data-scroll-target="#materials-methods">Materials &amp; Methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Women’s Participation in Global Climate Conferences</h1>
</div>



<div class="quarto-title-meta column-page-left">

    
  
    
  </div>
  


</header>


<p><strong>Jenna Graff, Gwynnie Hayes, &amp; Aria Whalen</strong></p>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>As the effects of climate change are felt increasingly across countries, exploring how effective environmental policy is created and enforced is becoming imperative to create a sustainable world. Given the global nature of climate change, we are interested in how international politics plays a role in decision making. One yearly conference held by the members of the United Nations Framework Convention on Climate Change (UNFCCC) is the Convention of the Parties (COP). These international meetings have been held yearly since 1995 (sans 2020) and offer a case study to understand how women have and continue to influence global environmental politics.</p>
<p>The makeup of actors in these conventions has primarily been older white men, which influences policy outcomes (Uhre, 2014). Studies have found conflicting evidence on a relationship between gender and the environment at a political level; while some find that female legislators are more concerned about environmental issues when compared to men, others find that after accounting for political party, gender is insignificant (Baraldi &amp; Fosco, 2025). Regardless, we believe that enough research has found a correlation between female legislators and environmental policies to merit examination of patterns in gender diversity in global environmental politics. Policies aimed to rectify inequality at an international level cannot be effective until we understand the factors that create it. Therefore, we hope to examine factors that may predict the proportion of women involved in the COPs for each nation over time.</p>
<p>Specifically, we are curious about how the attendance of women at COP meetings has changed over the 30 years that the convention has taken place. Much of this work is based on a similar examination by Andreas Uhre on the diversity of transnational actors across Global Environmental Summits. Uhre found that important predictors included financial resources and strength of democracy. On a national scale, factors we believe are important to examine include national measures of wealth, human rights, and political freedoms. We hypothesize that after accounting for a general increase in proportion of women participation in COPs over time, there will be predictive power in global indicators to explain differences in women participation among countries.</p>
</section>
<section id="materials-methods" class="level3">
<h3 class="anchored" data-anchor-id="materials-methods">Materials &amp; Methods</h3>
<p>To conduct this analysis, we brought together 5 datasets detailing Country Level statistics on COP meeting attendance from 1995-2024, Human Rights Index, Democracy Index, GDP per Capita, and Regional Location Data. To explore our questions we used these predictors to create a multilevel binomial model to predict the odds of a country’s COP delegate being a woman.<br>
The basis of our project is the COP meeting attendance data from the UNFCCC data, which was compiled into a dataset by <a href="https://www.nature.com/articles/s41597-024-03978-7#auth-Daria-Blinova-Aff1">Daria Blinova</a>, <a href="https://www.nature.com/articles/s41597-024-03978-7#auth-Rakesh-Emuru-Aff2">Rakesh Emuru</a> &amp; <a href="https://www.nature.com/articles/s41597-024-03978-7#auth-Benjamin_E_-Bagozzi-Aff1">Benjamin E. Bagozzi</a> for their article on “Individual attendance data for over 30 years of international climate change talks”. Using text extraction and OCR tools the researchers combed through thousands of pdf attendance rosters from each COP meeting to compile a dataset of the delegates party, name, honorific, job, and association, as well as the year of the COP meeting and where it was held. From this information, they created variables for the gender of the delegate based on honorific, and several other binary variables for the meeting type and delegation party (Blinova et al., 2024). To explore our questions, we filtered the data to only include governmental delegations, grouped the data by country and year, and counted by the number of delegates, so that we would ultimately end up with one row per country for each year they attended, and a total number of delegates that country sent that year. We totalled the number of female delegates per delegation, and divided that by the previous total to get a proportion of female delegates per country per year, our response variable.</p>
<p>&nbsp;Based on background research, we chose to look at three country level global indicators for our predictors. First, we joined GDP per Capita data from the World Bank as a level 2 predictor; these values didn’t change meaningfully among countries from 1995 to 2024, so the latest available data was joined as a constant variable between years. We then joined the Human Rights Index (HRI) from V-dem via Our World in Data as a level 2 predictor, for the same reason as above. To do this, we sliced the dataset to only include the most recent available data for each country, and joined that as a constant variable between years in our COP dataset. The value of the (HRI) ranges from 0 to 1 and is defined as, “the extent to which people are free from government torture, political killings, and forced labor, have property rights, and enjoy the freedoms of movement, religion, expression, and association” (V-Dem (2025) – processed by Our World in Data). Lastly, Democracy Index (DI) data was joined from the Economist Intelligence Unit via Our World in Data as a level 1 predictor that changes from year to year. The value of the DI ranges from 0 to 10 and is defined as, “extent to which citizens can choose their political leaders in free and fair elections, enjoy civil liberties, prefer democracy over other political systems, can and do participate in politics, and have a functioning government that acts on their behalf” (Economist Intelligence Unit (2006-2024) – processed by Our World in Data). It is also important to note that DI data was only available for certain years, resulting in a large quantity of missing data; the model should adjust for this automatically. Lastly, we joined regional data to have a continent level predictor.</p>
<p>To clean our data, we used tools to webscrape, filter, mutate, pivot, and extensively rename/recode variables to unify the full dataset we have now. NA’s in gender were dropped from the dataset. Furthermore, the variable for meeting year was centered on 1995 for meaningful analysis, and GDP per capita was logged to make comparisons meaningful. We also separated the original combined continent “Americas” into Northern America (USA &amp; Canada) and Latin America &amp; Caribbean (From Mexico through South America) for more specific comparisons.<br>
We chose to use a multilevel model to answer our research question as the data is nested by years in countries—analyzing it this way helps to control for the implicit bias caused by these nested units. Though an argument could be made that our data is also nested by continent, we chose to just use a two level approach as we have no continent level variables, and we are just interested in the impact of fixed effects from continents. We chose to specifically use a binomial multilevel model as our response variable is a proportion of an interest group divided by a total with multiple predictors. The model was weighted by the total number of delegates that attended. All analysis was done in R, and our model was run using the glmer function in lme4. Due to the complexity of our model, we just calculated ui for our random effects; the interpretation of this is that the effect of time is uniform for all countries.</p>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small">
<caption>Table 1. Summary Statistics for Numeric Variables</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">IQR</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n_miss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total Delegates</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4125</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">111</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">5391</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of Women</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1398</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">5391</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Proportion of Women</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5391</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">GDP Per Capita</td>
<td style="text-align: right;">154</td>
<td style="text-align: right;">256581</td>
<td style="text-align: right;">20304</td>
<td style="text-align: right;">7618</td>
<td style="text-align: right;">32670</td>
<td style="text-align: right;">22159</td>
<td style="text-align: right;">5391</td>
<td style="text-align: right;">132</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Human Rights Index</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5391</td>
<td style="text-align: right;">644</td>
</tr>
<tr class="even">
<td style="text-align: left;">Democracy Index</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5391</td>
<td style="text-align: right;">3032</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="columns">
<div class="column">
<p>To begin our modeling process, we looked at summary statistics for numeric variables. Table 1 shows the summary of the relevant numeric variables in our final model, excluding Meeting Year as it stayed relatively constant throughout the dataset. There is a large variation in the number of delegates from each country, which is why we used it as a weight later on in the modeling process. DI data is not recorded for every year, resulting in a high number of NA’s.</p>
<p>Fig. 1 shows four important relationships. First, there is a correlation between a country’s DI Score and the proportion of women in their delegation; there is a decent amount of variability from the line, but a clear trend exists. Over time, we see there is an increasing average proportion of women in COP delegations.</p>
</div><div class="column">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/stats316/figure 1.png" class="rounded-img img-fluid figure-img" width="540"></p>
<figcaption>Figure 1. Numeric Variable Correlation with Proportion of Women</figcaption>
</figure>
</div>
</div>
</div>
<div class="columns">
<div class="column">
<p>There may also be some potential explanatory value of a country’s HRI and log(GDP per Capita) on the proportion of women involved in a COP summit, though there is a much higher amount of variability. Log(GDP per capita) is especially variable.</p>
<p>From Fig. 2, we can see that Northern America has the highest intercept for the proportion of women in a country’s delegation. However, the slope seems to be slightly flatter than many of the other continents; Europe, Latin America &amp; The Caribbean, and Oceania are at a very similar proportion of women in the most recent meeting years despite having a much lower intercept. Africa and Asia have lower intercepts, as well as a slope comparable to Northern America.</p>
</div><div class="column">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/stats316/figure 2.png" class="rounded-img img-fluid figure-img" width="540"></p>
<figcaption>Figure 2. Each Continents Change in Proportion of Women Over Time</figcaption>
</figure>
</div>
</div><p>An unconditional growth model showed that meeting year is significant in predicting the proportion of women involved in COP delegations. This is unsurprising given the steady increase in proportion of women by meeting year shown in Figure 1. All subsequent models included our variables of interest: GDP per capita, HRI, and DI. Interactions between DI and level 2 variables were tested, but removed from the final model due to insignificance. Our final model is as follows:</p>
</div>
<div class="center-text">
<p><strong>Level 1:</strong></p>
</div>
<p><span class="math display">\[logodds_{ij} = a_i + b_i(Meeting Year_{ij}) + c_i(DI_{ij})\]</span></p>
<div class="center-text">
<p><strong>Level 2:</strong></p>
</div>
<p><span class="math display">\[a_i = \alpha_0 + \alpha_1(GDPperCapita_i) + \alpha_2(Continent_i) + \alpha_3(HRI_i) + u_i\]</span> <span class="math display">\[b_i = \beta_0  +  \beta_1(GDPperCapita_i)  +  \beta_2(Continent_i)  +  \beta_3(HRI_i)\]</span> <span class="math display">\[c_i = \gamma_0\]</span></p>
<div class="center-text">
<p><strong>Composite Model:</strong></p>
</div>
<p><span class="math display">\[logodds_{ij}= \alpha_0 + \alpha_1(GDPperCapita_i) + \alpha_2(Continent_i) + \alpha_3(HRI_i) + u_i + \]</span> <span class="math display">\[\beta_0(MeetingYear_{ij}) + \beta_1(GDPperCapita_i:MeetingYear_{ij}) + \]</span> <span class="math display">\[\beta_2(HRI_i:MeetingYear_{ij}) + \beta_3(Continent_i:MeetingYear_{ij} + \gamma_0(DI_{ij})\]</span></p>
<p><span class="math display">\[Where\ u_i\sim N(0, {\sigma_u}^2) \]</span></p>
<p>Finally, Table 2 includes the model output summary, including the raw estimate, the exponentiated estimate used for interpretation, standard error, and the estimate’s p-value. Six of our eighteen terms are interpreted in context, chosen for their significance to the model and relevance to our hypothesis. Terms involving continent are compared to Africa, due to it having the smallest intercept and largest interaction estimate, making it an ideal baseline for both interpretations.</p>
<div class="center-text">
<p>Table 2. Final Model Output Summary; *Interpreted Terms</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Estimate</th>
<th>Exponentiated</th>
<th>Std. Error</th>
<th>P-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>*Intercept</strong></td>
<td><span class="math inline">\(-2.550\)</span></td>
<td><span class="math inline">\(0.078\)</span></td>
<td><span class="math inline">\(0.384\)</span></td>
<td><span class="math inline">\(3.000 \times10^{-11}\)</span></td>
</tr>
<tr class="even">
<td><strong>Democracy Index (DI)</strong></td>
<td><span class="math inline">\(0.042\)</span></td>
<td><span class="math inline">\(1.043\)</span></td>
<td><span class="math inline">\(0.017\)</span></td>
<td><span class="math inline">\(0.013\)</span></td>
</tr>
<tr class="odd">
<td><strong>*Centered Meeting Year</strong></td>
<td><span class="math inline">\(0.034\)</span></td>
<td><span class="math inline">\(1.035\)</span></td>
<td><span class="math inline">\(0.013\)</span></td>
<td><span class="math inline">\(0.006\)</span></td>
</tr>
<tr class="even">
<td><strong>Logged GDP per Capita</strong></td>
<td><span class="math inline">\(-0.036\)</span></td>
<td>-</td>
<td><span class="math inline">\(0.051\)</span></td>
<td><span class="math inline">\(0.474\)</span></td>
</tr>
<tr class="odd">
<td><strong>*Human Rights Index (HRI)</strong></td>
<td><span class="math inline">\(1.022\)</span></td>
<td><span class="math inline">\(2.778\)</span></td>
<td><span class="math inline">\(0.246\)</span></td>
<td><span class="math inline">\(3.260 \times 10^{-5}\)</span></td>
</tr>
<tr class="even">
<td><strong>Northern America</strong></td>
<td><span class="math inline">\(0.984\)</span></td>
<td><span class="math inline">\(2.676\)</span></td>
<td><span class="math inline">\(0.456\)</span></td>
<td><span class="math inline">\(0.031\)</span></td>
</tr>
<tr class="odd">
<td><strong>Latin America &amp; The Caribbean</strong></td>
<td><span class="math inline">\(0.541\)</span></td>
<td><span class="math inline">\(1.718\)</span></td>
<td><span class="math inline">\(0.163\)</span></td>
<td><span class="math inline">\(0.0009\)</span></td>
</tr>
<tr class="even">
<td><strong>Asia</strong></td>
<td><span class="math inline">\(0.369\)</span></td>
<td><span class="math inline">\(1.447\)</span></td>
<td><span class="math inline">\(0.152\)</span></td>
<td><span class="math inline">\(0.015\)</span></td>
</tr>
<tr class="odd">
<td><strong>*Europe</strong></td>
<td><span class="math inline">\(1.060\)</span></td>
<td><span class="math inline">\(2.886\)</span></td>
<td><span class="math inline">\(0.197\)</span></td>
<td><span class="math inline">\(7.190 \times 10^{-8}\)</span></td>
</tr>
<tr class="even">
<td><strong>Oceania</strong></td>
<td><span class="math inline">\(0.563\)</span></td>
<td><span class="math inline">\(1.755\)</span></td>
<td><span class="math inline">\(0.298\)</span></td>
<td><span class="math inline">\(0.059\)</span></td>
</tr>
<tr class="odd">
<td><strong>Centered Meeting Year x Logged GDP per Capita</strong></td>
<td><span class="math inline">\(0.004\)</span></td>
<td>-</td>
<td><span class="math inline">\(0.002\)</span></td>
<td><span class="math inline">\(0.028\)</span></td>
</tr>
<tr class="even">
<td><strong>Centered Meeting Year x Human Rights Index (HRI)</strong></td>
<td><span class="math inline">\(-0.021\)</span></td>
<td><span class="math inline">\(0.980\)</span></td>
<td><span class="math inline">\(0.008\)</span></td>
<td><span class="math inline">\(0.008\)</span></td>
</tr>
<tr class="odd">
<td><strong>Centered Meeting Year x Northern America</strong></td>
<td><span class="math inline">\(-0.034\)</span></td>
<td><span class="math inline">\(0.966\)</span></td>
<td><span class="math inline">\(0.010\)</span></td>
<td><span class="math inline">\(0.0009\)</span></td>
</tr>
<tr class="even">
<td><strong>Centered Meeting Year x Latin America &amp; The Caribbean</strong></td>
<td><span class="math inline">\(-0.009\)</span></td>
<td><span class="math inline">\(0.991\)</span></td>
<td><span class="math inline">\(0.005\)</span></td>
<td><span class="math inline">\(0.073\)</span></td>
</tr>
<tr class="odd">
<td><strong>Centered Meeting Year x Asia</strong></td>
<td><span class="math inline">\(-0.023\)</span></td>
<td><span class="math inline">\(0.977\)</span></td>
<td><span class="math inline">\(0.005\)</span></td>
<td><span class="math inline">\(1.410 \times 10^{-6}\)</span></td>
</tr>
<tr class="even">
<td><strong>Centered Meeting Year x Europe</strong></td>
<td><span class="math inline">\(-0.034\)</span></td>
<td><span class="math inline">\(0.967\)</span></td>
<td><span class="math inline">\(0.006\)</span></td>
<td><span class="math inline">\(3.32 \times 10^{-8}\)</span></td>
</tr>
<tr class="odd">
<td><strong>Centered Meeting Year x Oceania</strong></td>
<td><span class="math inline">\(-0.015\)</span></td>
<td><span class="math inline">\(0.985\)</span></td>
<td><span class="math inline">\(0.009\)</span></td>
<td><span class="math inline">\(0.090\)</span></td>
</tr>
<tr class="even">
<td>*<span class="math inline">\({\sigma_u}^2\)</span></td>
<td><span class="math inline">\(0.127\)</span></td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
</tbody>
</table>
<p><strong>Intercept = 0.078:</strong> In 1995, an African country’s odds of a given delegate being a woman is 0.078 when that country’s GDP per capita, DI, and HRI are all zero. Centered Meeting Year = 1.035: For each additional meeting year since 1995, the odds of a delegate from an African country being a woman increase by 3.5% when GDP per capita and HRI are zero, and DI is controlled for.</p>
<p><strong>Human Rights Index = 1.108:</strong> To make this interpretation meaningful, we will assess changes of 0.1 in the HRI so we are not comparing polar opposite countries. For each additional 0.1 score of HRI, the odds of a delegate from an African country being a woman increase by 10.8% in 1995 when GDP per capita and DI are controlled for.</p>
<p><strong>Europe = 2.886:</strong> For European countries, the odds of a given delegate being a woman are 2.886 times higher than if the delegate were from an African country in 1995 when GDP per capita, DI, and HRI are controlled for.</p>
<p><strong>Meeting Year × Europe = 1.0:</strong> After controlling for DI and when GDP per Capita and HRI are zero, when a delegate is from a European country, the predicted odds that they are a woman remain the same for each additional year after 1995 – there is a 0% change. Comparatively, after controlling for DI and when GDP per Capita and HRI are zero, when a delegate is from an African country, the predicted odds that they are a woman increase by 3.5% for each additional year.</p>
<p><span class="math inline">\(\sigma_u{^2}\)</span> <strong>= 0.127:</strong> The country to country difference in odds of a delegate being a woman in 1995 is 0.127, after accounting for GDP per Capita, HRI, and DI.</p>
<p>These interpretations are relatively straightforward, but given real world conditions, interactions need more context. A real world interpretation of Meeting Year × Europe would not have GDP per capita or HRI at 0. A quick summary of our data reveals an average Log GDP per Capita and HRI in Europe are 10.4 and 0.866 respectively. Plugging those variables into the model would look like: <strong>exp(.034 + (10.4 × .0004) + (10.4 × -.021) + (1 × -.034)) = 0.986,</strong></p>
<p>When a delegate is from a European country, the predicted odds that they are a woman decreases by 1.4% every additional year after 1995, when Log GDP per Capita = 10.4, HRI = .866 (continental averages), and after accounting for DI.</p>
</section>
<section id="discussion" class="level3">
<h3 class="anchored" data-anchor-id="discussion">Discussion</h3>
<p>Our model shows clear evidence that a variety of Global Indicators are indeed influential in the proportion of women that enter into global environmental politics at COP meetings. There is a steady and significant increase to the proportion of women attending COP meetings. Furthermore, we found that increases in the Human Rights Index and Democracy Index are both significantly correlated with an increased probability of women joining a delegation at COP meetings. These findings are in line with past studies (Uhre, 2014). However, in our final model we did not find GDP per Capita to be a significant variable on its own, though it was when interacting with the meeting year. This is starkly in contrast to Uhre’s other finding, which was that financial resources are significantly correlated with the diversity of participation in Trans-National Actors at Global Environmental Political Meetings. Notably, GDP per Capita was significant before adding in continent level predictors, signalling that GDP per Capita is likely still significantly correlated with the proportion of women but is being overexplained by Continents.</p>
<p>The most common significant interaction was on meeting year, with all predictors besides DI interacting significantly, and being included in the final model. While Continent × Meeting Year are easily interpreted as above, that is not truly representative of the whole story. As mentioned in the results, setting GDP per Capita and HRI to 0 to interpret a model is not realistic. By adjusting the model to include continental averages we see that Europe’s effect on proportion over time shifts from flat to negative. This difference reveals that real world applications of this data are highly complex and should include a more nuanced interpretation.</p>
<p>These results show a clear trend that an increase in governmental resources, democracy, and human rights are impactful on the proportion of women involved in their country’s environmental politics. These findings are crucial to overall equality, but this shift towards more feminine politics also may also have impacts on sustainable measures that come out of these meetings (Baraldi &amp; Fosco, 2025). Based on this model, countries that wish to improve their gender equality in environmental politics (specifically at COP meetings) should put an increased level of effort into their fairness of democracy and the human rights of their citizens.</p>
<p>The strength of our analysis is that it builds upon work from past papers to connect COP data to global indicators and paint a new more full image of what factors lead to increased diversity in a section of global environmental politics. The weakness of our analysis is in the complexity of our model. Due to the size and complexity of our model, we could not explore random effects on a meaningful level and our model repeatedly failed to reach convergence. Possible confounding variables in our study might include individual government gender equality statistics or other global indicators we didn’t include in our study. Future studies should test the impact of a meeting being in the same region as the delegation’s country, as well as other indicators such as birth rates or rates of women’s education.</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<p>Baraldi, A. L., &amp; Fosco, G. (2025). Clearing the air: Women in politics and air pollution. Journal of Environmental Economics and Management, 130, Article 103106. https://doi.org/10.1016/j.jeem.2024.103106</p>
<p>Blinova, D., Emuru, R., &amp; Bagozzi, B. E. (2024). Individual attendance data for over 30 years of international climate change talks. Scientific Data, 11(1), Article 1134. https://doi.org/10.1038/s41597-024-03978-7</p>
<p>“Data Page: Democracy index”, part of the following publication: Bastian Herre, Lucas Rodés-Guirao, and Esteban Ortiz-Ospina (2013) - “Democracy”. Data adapted from Economist Intelligence Unit, Gapminder, Various sources. Retrieved from https://archive.ourworldindata.org/20251209-133038/grapher/democracy-index-eiu.html [online resource] (archived on December 9, 2025).</p>
<p>Lukes. (n.d.). ISO-3166-countries-with-regional-codes/all/all.csv at master · Lukes/ISO-3166-Countries-with-regional-codes. GitHub. https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv</p>
<p>Uhre, A. N. (2014). Exploring the diversity of transnational actors in global environmental governance. Interest Groups &amp; Advocacy, 3(1), 59-78. https://doi.org/10.1057/iga.2013.13</p>
<p>V-Dem (2025) – processed by Our World in Data. “Human rights index – V-Dem” [dataset]. V-Dem, “Democracy report v15” [original data]. Retrieved November 18, 2025 from https://archive.ourworldindata.org/20251118-091644/grapher/human-rights-index-vdem.html (archived on November 18, 2025).</p>
<p>World Bank Open Data. (n.d.). World Bank Open Data. Retrieved November 21, 2025, from https://data.worldbank.org</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>